version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: jupyterlab
    user: "1000:1000"
    container_name: jupyterlab
    ports:
      - 9999:8888
    volumes:
      - shared-workspace:/opt/workspace
      - /home/thusitha/work/bigdata/codes:/opt/workspace/code
      - /home/thusitha/work/bigdata/:/opt/workspace/data
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
      - /home/thusitha/work/bigdata/:/opt/workspace/data
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=6
      - SPARK_WORKER_MEMORY=16G
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
      - /home/thusitha/work/bigdata/:/opt/workspace/data
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=6
      - SPARK_WORKER_MEMORY=16G
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
      - /home/thusitha/work/bigdata/:/opt/workspace/data
    depends_on:
      - spark-master
networks:
  default:
    external:
      name: bridge-network
volumes:
  shared-workspace:
    external: true